# application.yml : web.xml, root-context.xml, servlet-context.xml의 합본
spring:

  mvc:
    view:
      prefix: /WEB-INF/views/ # 앞에 붙는 경로
      suffix: .jsp            # 뒤에 붙는 경로
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://kms.mysql.database.azure.com:3306/bloghhr?serverTimezone=Asia/Seoul
    username: master
    password: rlaalstj!234
  
  jpa:
    open-in-view: true
    hibernate:
#      ddl-auto: create # 프로젝트 생성시만 create 해준다. - 기존 테이블 삭제 후 재생성 >> 추후 update
      ddl-auto: update # 프로젝트 생성시만 create 해준다. - 기존 테이블 삭제 후 재생성 >> 추후 update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false  # JPA가 사용하는 기본 넘버링 전략을 따르지 않음
      id: # MySQL의 auto_increment 전략
        new_generator_mappings: true
    show-sql: true
    properties:
      hibernate.format_sql: true
  
  jackson:
    serialization:
      fail-on-empty-beans: false
    
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true